---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.uptimerobot.com/v3/monitors
polling_headers: authorization=Bearer%20{{ uptimerobot_api_key }}
polling_body: ''
id: 98765
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Displays the status of UptimeRobot monitors
  github_url: https://github.com/stephenyeargin/trmnl-uptimerobot
  learn_more_url: https://uptimerobot.com/
  email_address: stephen@yearg.in
- keyname: uptimerobot_api_key
  field_type: password
  name: UptimeRobot Authorization Header
  description: Create a read-only Main API Key <a href="https://dashboard.uptimerobot.com/integrations" class="underline">here</a>.
  placeholder: somelongstringgoeshere1234
name: UptimeRobot
refresh_interval: 15
